def add(a, b):
    """
    add two arguments .
    AI-generated by Ponicode.
    """
    return a + b

def greet():
    """
    greet .
    AI-generated by Ponicode.
    """
    print("Hello World")
    print('Hi')
    print(""" Yo """)